# Generated by Django 5.2.1 on 2025-05-16 16:45

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_utente', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('password_hash2', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='I gruppi a cui appartiene questo utente.', related_name='utenti_gruppi', to='auth.group', verbose_name='gruppi')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='I permessi specifici per questo utente.', related_name='utenti_permessi', to='auth.permission', verbose_name='permessi utente')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causale', models.CharField(max_length=255)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spese', to='api.gruppo')),
                ('utente_pagante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spese_pagante', to='api.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='api.gruppo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='api.utente')),
            ],
        ),
        migrations.AddField(
            model_name='gruppo',
            name='creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppi_creati', to='api.utente'),
        ),
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField(blank=True)),
                ('spesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debiti', to='api.spesa')),
                ('utente_debitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debiti', to='api.utente')),
            ],
        ),
    ]
