# Generated by Django 5.2.1 on 2025-05-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='password_hash2',
        ),
    ]
