# Generated by Django 5.2.1 on 2025-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_utente_password_hash2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='utente',
            name='password',
            field=models.CharField(default='password', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
